# Model arguments
model_name_or_path: distilbert/distilbert-base-uncased
model_revision: main
tokenizer_name_or_path: distilbert/distilbert-base-uncased
torch_dtype: float16

# Data training arguments
dataset_mixer:
  imdb: 1.0
  sst2: 1.0
preprocessing_num_workers: 8
max_seq_length: 384

# CPT specific settings
mlm_probability: 0.15

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 4
lora_alpha: 8 # Lowered for more stable adaptation
lora_dropout: 0.2 # Increased to improve regularization
lora_target_modules:
  - q_lin
  - k_lin
  - v_lin
  - out_lin
  - ffn.lin1
  - ffn.lin2

# Training config
do_train: true
do_eval: true
eval_strategy: "steps"
eval_steps: 1000 # Less frequent to save resources

num_train_epochs: 5 # Increased epochs to allow for early stopping
max_steps: -1
gradient_accumulation_steps: 2 # Increases effective batch size while lowering memory usage
gradient_checkpointing: true # Enabled to help with memory management
learning_rate: 0.0001 # Lowered for better stability with large batch sizes
weight_decay: 0.02 # Increased for better generalization
logging_steps: 500 # Adjusted to reduce verbosity

# Early stopping (added to avoid overfitting)
early_stopping_patience: 3 # Stop after 3 evaluations without improvement
early_stopping_threshold: 0.01 # Minimum improvement threshold
load_best_model_at_end: true

# Optimizer settings
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.1 # Increased warmup to improve stability during initial training phase

# Training parameters
per_device_train_batch_size: 128 # Reduced to keep memory within limits when accumulating gradients
per_device_eval_batch_size: 256
remove_unused_columns: true
seed: 42

# Save settings
save_strategy: "steps"
save_steps: 2000
save_total_limit: 2
push_to_hub: true
hub_model_id: wsklee/distilbert-sentiment-cpt
hub_strategy: every_save
hub_token: null # Will use token from huggingface-cli login
output_dir: data/distilbert-sentiment-cpt

# Reporting
report_to:
  - wandb
