# Model arguments
model_name_or_path: distilbert/distilbert-base-uncased
model_revision: main
tokenizer_name_or_path: distilbert/distilbert-base-uncased
torch_dtype: float16

# Data training arguments
dataset_mixer:
  imdb: 1.0
  sst2: 1.0
preprocessing_num_workers: 8
max_seq_length: 384

# CPT specific settings
mlm_probability: 0.15

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_r: 4
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - q_lin
  - k_lin
  - v_lin
  - out_lin
  - ffn.lin1
  - ffn.lin2

# Training config
do_train: true
do_eval: true
eval_strategy: "steps"
num_train_epochs: 3
max_steps: -1
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 0.0005
weight_decay: 0.01
logging_steps: 200

# Optimizer settings
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.05

# Training parameters
per_device_train_batch_size: 256
per_device_eval_batch_size: 512
remove_unused_columns: true
seed: 42

# Save settings
save_strategy: "steps"
save_steps: 2000
save_total_limit: 2
push_to_hub: true
hub_model_id: wsklee/distilbert-sentiment-cpt
hub_strategy: every_save
hub_token: null # Will use token from huggingface-cli login
output_dir: data/distilbert-sentiment-cpt

# Reporting
report_to:
  - wandb
