# Model arguments
model_name_or_path: distilbert/distilbert-base-uncased
model_revision: main
tokenizer_name_or_path: distilbert/distilbert-base-uncased
torch_dtype: float16

# Data training arguments
dataset_mixer:
  imdb: 1.0
preprocessing_num_workers: 4
max_seq_length: 256

# CFT specific settings
temperature: 0.06 # Temperature parameter for contrastive loss

# LoRA arguments
use_peft: true
peft_lora_r: 4
peft_lora_alpha: 16
peft_lora_dropout: 0.2
peft_lora_modules:
  - q_lin
  - k_lin
  - v_lin

# Training config
do_train: true
do_eval: true
evaluation_strategy: "steps"
eval_steps: 500
metric_for_best_model: "loss"
greater_is_better: false

num_train_epochs: 4
max_steps: -1
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 0.00002
weight_decay: 0.01
logging_steps: 200

# Early stopping (added to avoid overfitting)
early_stopping_patience: 3 # Stop after 3 evaluations without improvement
early_stopping_threshold: 0.01 # Minimum improvement threshold
load_best_model_at_end: true

# Optimizer settings
optim: adamw_torch
lr_scheduler_type: cosine_with_restarts
warmup_ratio: 0.1

# Training parameters
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
remove_unused_columns: false
seed: 42

# Save settings
save_strategy: "steps"
save_steps: 1000
save_total_limit: 2
push_to_hub: true
hub_model_id: wsklee/distilbert-sentiment-cft-v3
hub_strategy: every_save
hub_token: null # Will use token from huggingface-cli login
output_dir: data/distilbert-sentiment-cft-v3

# Reporting
report_to:
  - wandb
