# Model arguments
model_name_or_path: distilbert/distilbert-base-uncased # Path to your SFT model
model_revision: main
tokenizer_name_or_path: distilbert/distilbert-base-uncased
torch_dtype: float16

# Data training arguments
dataset_mixer:
  imdb: 1.0
  sst2: 1.0
preprocessing_num_workers: 4
max_seq_length: 256

# DPO specific settings
beta: 0.1
reference_model: data/distilbert-sentiment-sft # Your SFT model as reference

# LoRA arguments
load_in_4bit: true
use_peft: true
lora_r: 4
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - q_lin
  - k_lin
  - v_lin
  - out_lin
  - ffn.lin1
  - ffn.lin2
  - pre_classifier
  - classifier

# Training config
do_train: true
do_eval: true
eval_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 0.000005 # 5e-6 written as explicit float
logging_steps: 50
lr_scheduler_type: cosine
max_steps: 1000
output_dir: data/distilbert-sentiment-dpo

# Hub settings
push_to_hub: true
hub_model_id: wsklee/distilbert-sentiment-dpo # Replace with your username
hub_strategy: every_save
hub_token: null # Will use token from huggingface-cli login

# Training parameters
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
remove_unused_columns: true
report_to:
  - wandb
save_strategy: steps
save_steps: 200
seed: 42
warmup_ratio: 0.1
