# Model arguments
model_name_or_path: wsklee/distilbert-sentiment-yelp-sft
model_revision: main
tokenizer_name_or_path: wsklee/distilbert-sentiment-yelp-sft
torch_dtype: float16

# Data training arguments
dataset_mixer:
  yelp_polarity: 1.0
preprocessing_num_workers: 4
max_seq_length: 256

# CFT specific settings
temperature: 0.05 # Temperature parameter for contrastive loss

# LoRA arguments
use_peft: true
peft_lora_r: 8
peft_lora_alpha: 16
peft_lora_dropout: 0.2
peft_lora_modules:
  - q_lin
  - k_lin
  - v_lin

# Training config
do_train: true
do_eval: true
evaluation_strategy: "steps"
eval_steps: 200
metric_for_best_model: "eval_f1"
greater_is_better: true
eval_accumulation_steps: 1 # Add this to control memory usage during eval
include_inputs_for_metrics: true # Add this to ensure inputs are passed to compute_metrics

num_train_epochs: 5
max_steps: -1
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 0.00002
weight_decay: 0.01
logging_steps: 200

# Early stopping (added to avoid overfitting)
early_stopping_patience: 3
early_stopping_threshold: 0.01 # Minimum improvement threshold
load_best_model_at_end: true

# Optimizer settings
optim: adamw_torch
lr_scheduler_type: cosine_with_restarts
warmup_ratio: 0.1

# Training parameters
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
remove_unused_columns: false
seed: 42

# Save settings
save_strategy: "steps"
save_steps: 2000
save_total_limit: 2
push_to_hub: true
hub_model_id: wsklee/distilbert-sentiment-yelp-sft-cft
hub_strategy: every_save
hub_token: null # Will use token from huggingface-cli login
output_dir: data/distilbert-sentiment-yelp-sft-cft

# Reporting
report_to:
  - wandb
